name: Deploy CloudFormation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name shopfast-auth-dev \
            --template-file templates/userpool.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
                StackName=shopfast-auth-dev \
                AuthDomainName=auth2-dev.denilparmar.work \
                ShopFastCognitoCert=arn:aws:acm:us-east-1:388742983609:certificate/e74d25c6-f80b-48d6-a819-7f2aae1709b3

      - name: Deploy API Gateway Certificate stack
        run: |
          aws cloudformation deploy \
            --stack-name shopfast-api-cert-dev \
            --template-file templates/api-certificate.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
                ApiCustomDomainName=api-dev.denilparmar.work

      - name: Deploy Payments DynamoDB Table
        run: |
          aws cloudformation deploy \
            --stack-name shopfast-dynamodb-table-dev \
            --template-file templates/payments-dynamodb-table.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
                TableName=Shopfast-Payments

      - name: Deploy Stripe Secret
        run: |
          aws cloudformation deploy \
            --stack-name shopfast-stripe-secret-dev \
            --template-file templates/stripe-secret.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
                Environment=dev

